### ISSUE TITLE
Users may accidentally send messages to wrong contacts

### ISSUE THREAD

**Issue by nidico** [wireapp/wire#104]
As many users don't use a clear identifier as their profile name, but e.g. only their first name or a pseudonym - be it due to privacy concerns with the name discovery (e.g. "I don't want to be discovered by my real name") or due to pure laziness -, other users may accidentally send private messages to the wrong user (e.g. with the same name) or accidentally add wrong contacts to groups.

As any message may contain sensitive information which may not be read by any other person than the intended recipient(s), **this issue is critical**.

It looks like the most intuitive solution seems to be to allow users to add a local alias to a contact (local quasi-rename). Those contact aliases need to be synchronized throughout all devices of a user.

This has been proposed many times, in particular in wireapp/wire-desktop#44 (this was the master issue until now, however in the wrong repo, as the issue belongs in wireapp/wire, as it affects the entire platform).

Another alternative proposal was added in #64, namely to generally show other contact's profile username instead of their profile "name". I wouldn't consider this proposal as an acceptable solution of this issue, as it would render the "name" concept almost useless (what would be the purpose if it wasn't shown?).

Thanks in advance for a fix!

**Comment by shatterproof** [comment]
Snapchat implements similar functionality where a user's initial chosen name is displayed, which can then be edited locally by other users. This is especially important when multiple users have the same chosen name along with a cryptic username, making it hard to determine which contact is who, as mentioned above.

**Comment by thenktor** [comment]
Renaming contacts IMHO is the most important thing that Wire is missing.

**Comment by kristin-wire** [comment]
Hi there, thanks for this request - it makes a lot of sense. Just to set expectations though, while this is a good request, it's lower down on the list.

Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.

**Comment by dwt** [comment]
Uhm, not sure what you mean: You closed this bug because you want to implement it at some point?

Maybe I'm getting this wrong, but if you want to encourage outside contributors to have a chance to do this, you will have to keep it open (marked as 'please contribute' or something like this? No?

**Comment by nidico** [comment]
Adding to this, marking this as closed will just lead to yet more duplicates as users only search for open issues in open tickets.

**Comment by Vintodrimmer** [comment]
I don't understand your way of managing "issues".

Most of the time it's open unless solved or deemed unimportant. Otherwise I feel this just adds to confusion.

**Comment by richpersaud** [comment]
Seconded.  Moving open-source enhancement requests to a private bug tracker causes:

- duplicate requests for initial fixes
- loss of improvement ideas for initial fixes
- loss of history (incl. votes) for long term open issues
- public cost of collating info from multiple issues
- inability to distinguish between invalid, open-but-not-reviewed, open-but-unplanned, open-but-planned, in-progress, fixed, etc.

Please use issue statuses, instead of treating issues like emails that need to be copied to a private database then deleted publicly.

Could Wire allow an open-source contributor to help moderate open-source issue reports?  If Wire needs an issue reporting channel for non-open features, that can be hosted outside of  Github.
