### ISSUE TITLE
Feature: Allow adjustment of font size in preferences

### ISSUE THREAD

**Issue by liam-tc** [wireapp/wire#121]
I find the default font to be too large. Would it be possible to allow a simple preference option to change the font size that displays in chats?

**Comment by kristin-wire** [comment]
On mobile, you can adjust font size in your device settings, and Wire will follow. Request noted for desktop.
We have logged this in our internal feature request database for tracking, and will close this request here.

**Comment by fl1tz** [comment]
I (want to) use Wire Desktop with Manjaro. But the font in the chat is practically unreadable. The letters merge into each other, they are out of focus gray and the size is unfortunately not selectable. Since there are no settings, you can not do anything. It would be good to set the color of the font to black and white and make the font selectable. Not all people have eyes like a lux.
