### ISSUE TITLE
Feature request: Backups

### ISSUE THREAD

**Issue by t-aus-m** [wireapp/wire#136]
I know, that it isn't a bug, nor a missing feature but rather a feature, but I get really annoyed by the fact, that you can not see previous messages on a new device. This could have some major drawbacks, say a person, who only uses one device (e.g. their phone) getting a new phone, for whatever reason. They will not be able to see old messages anymore, which is imo a valid reason to not use wire at all.

And this is where my request comes from:
I would like to have some kind of backup-possibilitiy. Like basically any other recognized messenger has. Please make it like WhatsApp (but better), where Backups are created once every 24h and then (optionally) uploaded (encrypted of course) to some kind of cloud storage (support for all the popular ones, as well as Owncloud/Nextcloud or WebDAV in general would be greatly appreciated).
Imo you should then be able, once you setup a new device, to choose an existing backup to recover all the messages and media from.

**Comment by user9209** [comment]
+1

The problem is that most people use wire not like a phone call, they use it like email.
This means, you want to know you former history.
If Backup is not a optinion, a forced self destruction after 1 week may be a solution, so people learn,
content of wire should non persistent.

So please choose between:

persistent content: must include backups and account transfer (may done by creating backup and restoring on other account)

or

non persistent content: force user to recognise this fact, as some people practicaly achieve using it with persistent content

Currently you must accept, that you can lose all your data on wire in the next moment, when the client is losing this key pair.
Technical problems, reinstall of the client-software, stollen or lost device, reinstall of the operatinal system, replacing hardware device and many more situations will clear all you data.

So please provide some kind of backup or export.

Thanks in Advance

**Comment by user9209** [comment]
related issue:

https://github.com/wireapp/wire/issues/116

Depending, how the implementation may look.

**Comment by Namnodorel** [comment]
This is already kinda-possible, although not for the average user. But if you have a rooted device or are willing to root it, you can use Titanium Backup: It allows you to make a complete and between-devices-movable backup of Wire, and you can set up scheduled backups as well. Not optimal, but until the official feature is there it works.

**Comment by trymeouteh** [comment]
+1

**Comment by kristin-wire** [comment]
Thanks all for your feedback. Working on this is on our 2018 roadmap.
