### ISSUE TITLE
Feature Request: @ mentions

### ISSUE THREAD

**Issue by timbedard** [wireapp/wire#221]
Of all the features I miss from Slack, this one is the most painful and honestly the only one I care about. It is the only thing I look for in the "What's New" updates. Every time. Our dev team would implement it for the desktop client ourselves if y'all allowed feature contributions.

For the love of all that is good in the world, please add this to the clients. Please.

Much love and keep up the good work.

**Comment by cardassian-tailor** [comment]
depending on your seriousness and level of expertise in the languages used - i would highly suggest you at least ping some of the active developers to make sure no duplicate efforts occur and no time wasted.

**Comment by cardassian-tailor** [comment]
#170  duplicate

**Comment by cardassian-tailor** [comment]
> I agree 100%. Much needed. I will mention, not sure how serious you are about code contributions, on the main page of the wire github there is a section for code contributions (very end of the page). Sign their contributor agreement and you could fork and submit pull requests to add this feature.
> 
> https://github.com/wireapp/wire

ahh I see what you mean 

_

> We accept only bug fixes and code improvements. We cannot accept new features, UI or UX changes – these are decided on and built by the Wire development team.




_

**Comment by cardassian-tailor** [comment]
I think this would be a good time to discuss how such a notification system would work - as I could see the argument being made that mentions isnt technically a new feature, but an improvement upon the already existing usernames and notification system. 

Currently - you are notified after every new message in a conversation. How would this change with mentions? Would mentions be a muting option so that instead of silencing the entire channel, you still receive notifications if you are specifically mentioned? Would this be a per-conversation setting or a global setting? Would mentions have a separate area for historical reference ( a history of past mentions)?

**Comment by phifa** [comment]
So, we have ping and mention @ username. But its current implementation seems useless. I don't see what the point of it is right now. 
The way this should actually work: 
You can mute a specific group or conversation. And by mute mean not just audio, but also notifications. When someone hits @myUser or @group or @everyone, then I would expect to be notified. Thats the way it makes sense. You can have groups muted to avoid the noise, but if something important comes up, the sender can just notify the whole group. 

Can you comment on this Wire? What are your thoughts? @timbedard @cardassian-tailor

**Comment by Mansarde** [comment]
@phifa It seems that functionality kind of exists, but exclusively for Pro:
> Wire Pro accounts have an additional per-conversation setting to get notifications for all messages, only for mentions, or mute the chat completely.
Source: https://wire.com/en/blog/mentions/

So I guess non-pro users are [SOL](https://en.wiktionary.org/wiki/SOL), unfortunately.
 :´(
