### ISSUE TITLE
Online Status of Contacts

### ISSUE THREAD

**Issue by user9209** [wireapp/wire#24]
Hello,
thank you for the great work.

Please consider inserting an online status.
Voice- and Video-Calls try to connect even if the user is offline and a timer closes the connection after a while.
With an online status the call can stopped immediately if the contact is offline.

Another reason for an online status:
Some people use a messenger from a selection of running messengers where the contact is currently online.
If Wire does not provide a status information, it is an obstacle to use Wire in this situation.

I know an online status may result in tracking users being online or offline.

Thanks in advance

**Comment by alugarius** [comment]
Define offline please...
If my phone is on and I am not currently using Wire, I want to be able to get Calls.

**Comment by user9209** [comment]
> It makes sense if every device of the opponent is turned off or Wire can't connect to the web
Yes, exactly what I meant

**Comment by twosky2000** [comment]
A status like Skype would be nice. To see if some one is busy or does't want a disturbance(Messanges and calls could be easily muted).
Also a timed reset could be an option, like the destructive Messages. You could be online and after 3 hours you would get automatically offline.

**Comment by shvchk** [comment]
See also [discussion of the same feature in Wire Desktop issue queue](https://github.com/wireapp/wire-desktop/issues/128)

**Comment by avently** [comment]
Would be great to have this feature but... We don't need this. Because Wire is about privacy and we should always think about it. Yes, this feature is useful but not here. Sometimes i want to know when someone was online but i never want to share when i was online:)
So my idea is to avoid online status in Wire. You can use other non-private messagers like WhatsApp for that purpose.

**Comment by Namnodorel** [comment]
@avently Yes, Wire has privacy/security as a huge selling point, but usability is also important (otherwise we wouldn't need such a fancy design, or what good is it for privacy to send GIFs?). Many users want such a feature, and as long as it is opt-in (which means no information can be leaked accidentally), I don't really see a big privacy problem here. Users being able to choose exactly where they want to draw the line between the privacy they want and the usability sounds like a good thing to me.

**Comment by shvchk** [comment]
> We don't need this. Because Wire is about privacy

Those who don't need this feature could just... not use this feature.

**Comment by oscalation** [comment]
a feature that gives the user the option to place themself into a less secure state isnt a feature, its a regression. 

The question is, does online status notifications place user privacy, even if its opt in, at risk? 

The notification that a message was delivered seems, at least to me, sufficient. This tells you that the recipient has wire installed, your message was delivered, and if they check it and CHOOSE to reply then you will be notified.

**Comment by shvchk** [comment]
> a feature that gives the user the option to place themself into a less secure state isnt a feature, its a regression.

Following this logic, noone should install Wire or any other software, as it is by definition less secure than no software — the most secure system is that turned off with wiped hard drive, anything more is not a feature, it's a regression.

**Comment by avently** [comment]
@shvchk это не отменяет того факта, что человек прав. Это действительно регрессия, а никак не прогресс.

**Comment by Namnodorel** [comment]
I'd say it is a feature, or lets say, an option. Often convenience is at the expense of security, but I think we should leave to the user how much security they want and need. As of now, Wire just decides for the user that security is more important than convenience. But Wire shouldn't only be made for people who want to maximise their security. It needs to be an opt-in feature, yes, but just making the opposite choices to WhatsApp when it comes to convenience vs. security is not the way to go.

**Comment by shvchk** [comment]
@avently, it would be a regression if users would be forced to use it, or if Wire would silently change status without user's explicit intention or consent (as Skype does). If statuses are optional, and user is informed about potential privacy issues (if any), and default behavior is the same as now, where is regression?

**Comment by avently** [comment]
@shvchk большинство пользователей не разбирается в технологиях. Они надеются взять инструмент, который сделан профессионалами и работает на все 100%. И люди действительно не будут понимать нюансов и того, к чему они могут привести. Именно поэтому нужно думать за юзера в вопросах безопасности. Пользователь может ошибиться. Потом это выйдет ему боком и ситуация окажется в новостях (как было много раз с телеграммом). И именно инструмент будут считать ненадежным, а не пользователя - глупым. 
Дальше говорить об этом нет смысла. Самое важное мнение (разработчиков) мы уже знаем. Сколько бы ты не поставил дизлайков:)

**Comment by Namnodorel** [comment]
Which is why we'd probably need a popup informing the user of the potential security risk. And because it is opt-in, I also wouldn't say it's too dangerous for new users - if I was someone who wouldn't be really "into tech", I'd rather keep my current settings than risking to break something. If we put the option into a category like "Settings with potential privacy risks", it would scare everyone off who doesn't exactly know what they are doing.

And yes, we know the developers opinion - but opinions can change, and if a) enough people want it and we b) offer a concept that doesn't violate Wire's basic security attitude while satisfying those who need it, I don't see why it wouldn't be reconsidered to implement it.

**Comment by shvchk** [comment]
@avently, you can hover on dislike icon and see who disliked your messages, there is not a single one dislike from me in this thread. Now back to the issue: problems with users competence do exist, and this is precisely why we are talking about it being an opt-in with current behavior staying as default and that users should be informed on potential privacy issues when enabling this feature. I don't know which Telegram issues you are referring to, but approach suggested here is exactly the opposite: secure and privacy-concerned default and an opt-in feature with informative notice for those who wants it. Compare it with Telegram's secure chats for example: less secure default and an opt-in e2e encryption — again, this is exactly the opposite to the approach suggested here.

**Comment by oscalation** [comment]
Here is a good question: 

If it is opt in, turned off by default, and IF it can be implemented securely without loss of privacy ... would anyone object to the feature?

I can say that I would not object and would welcome the additional functionality. 

Now the harder discussion must occur. How would devices signal to each other or to a wire server that they are "online"  without leaking whom is talking to each other, or tracking user devices, or tracking users. 

Someone give some credible details to this and then the feature can be considered, but until then we have to conclude that its not possible to implement securely.

**Comment by PicoGeyer** [comment]
I just want to add another perspective despite the appearance that developers are not interested ;-) In our company we used the presence feature quite heavily. We use don't disturb when we are in meetings or when we need to focus. We used away to notify others that we aren't at our desk (and they shouldn't wait for a response). Only in urgent situations do people message despite DND/away/offline statuses. Currently I hesitate to use wire until I know via other means that the person is available.

**Comment by Namnodorel** [comment]
> Now the harder discussion must occur. How would devices signal to each other or to a wire server that they are "online" without leaking whom is talking to each other, or tracking user devices, or tracking users.

I'm not sure what your problem is here. The Onlinestatus-Packet would be sent just like a regular message - maybe every few minutes so the server can automatically display you as offline when Wire stops sending status packets. But for tracking/metadata you wouldn't get to know anything more than you already do with regulare messages.

**Comment by shvchk** [comment]
AFAIU, your connection with the server is kept alive with periodic "ping" packets anyway, so no additional privacy issues arise if you also send "online" or "busy" status messages to the server. You also would request server for statuses of all your contacts, without distinction who you are talking to or not, so no leaking here too (who is in your contact list is now known to the server anyway, AFAIK).

**Comment by wmengli** [comment]
Hi all,

Lot's of discussions here :)

This is one of our top feature request and we have lots of internal debates too. To show or not to show is going to please/upset some of the people. We are not looking into changing it now but might revisit this in the future. No concrete plan yet but definitely we are aware of it and did not forget about it.
Sorry we will close this for now. You can be assured that it's logged in our feature request system. Thank you all for sharing your thoughts!

Best wishes,
Wire Support Team

**Comment by sebastian-brandt** [comment]
Sorry for commenting on a closed old ticket. 

We were recently considering Wire to replace Skype for communication with teleworking colleagues (mostly because of Wire's end-to-end encryption) and having an availability status would be helpful before initating voice or video calls. Without it we'd have to do the "are you there ... <wait> ... yes ... <initiate call>" dance multiple times a day.

I completely agree that this should be an opt-in feature but not having it at all is just a bummer.

Are there any news about to support this feature now as of 2019?
