### ISSUE TITLE
Wire-desktop  in Debian doesn't start | error message in the post

### ISSUE THREAD

**Issue by NoCodeForOldMen** [wireapp/wire#247]
Hi,

for about two weeks I haven't been able to start the wire-desktop on my notebook (Thinkpad 23 gen2 2017) which is running 'Debian testing'.
I think it happened after updating, so here is my log from the terminal:

`$wire-desktop
`
Reading profile /etc/firejail/wire-desktop.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 11317, child pid 11318
Warning: skipping pki for private /etc
Warning: skipping crypto-policies for private /etc
Private /etc installed in 52.33 ms
Error fcopy: invalid file /usr/bin/wire-desktop
Error: failed to run /usr/lib/x86_64-linux-gnu/firejail/fcopy
Error: proc 11317 cannot sync with peer: unexpected EOF
Peer 11318 unexpectedly exited with status 1

Maybe someone has an idea.
Thank you in advance.

**Comment by marcoconti83** [comment]
Hi @NoCodeForOldMen , 
thanks for letting us know! This is a desktop-app specific issue. In order to have this looked at by the right people, could you please open this issue in the wire-desktop repository instead? I'm closing this issue, you can copy-paste this issue there: https://github.com/wireapp/wire-desktop/issues/new

Thanks!
