### ISSUE TITLE
[feature request] connection requests should include a message

### ISSUE THREAD

**Issue by libBletchley** [wireapp/wire#250]
When someone with a user id like `ButtHead` makes a connection request, the recipient doesn't necessarily know the sender's real identity.  Obviously it's a bad idea to select a user id that reveals your real identity because that metadata is not encrypted.  So the recipient has to take a chance and accept, or they say "who is this weirdo" and block.  The connection request needs to come with an encrypted message so the sender can say something like "Hi this is Jerry" or whatever.

This feature request is separate but similar to https://github.com/wireapp/wire/issues/249.  If #249 gets implemented then maybe this one isn't needed.

I should also point out there may be some risk here.. if this feature is implemented, perhaps spammers will exploit it.  So countermeasures for that should be considered at the same time.

**Comment by marcoconti83** [comment]
Hi @libBletchley ,

You have a good point about clarifying who you are, but we have to balance the usability against the potential exploitation of this feature for non legit uses. You are right about the "spam" concern. We don't want to allow someone that you didn't authorize to write to you, and for this reason we don't want to allow custom connection messages. This is a very concrete concerns and we have already encounter plenty of spammers exploiting any chance they have to send spam or inappropriate content to users that they were not connected to, and we don't want to open another channel for them. We could try to find a way to "sanitize" introduction messages to remove sensitive content or spam, but since Wire is translated in many languages it's not so straightforward,  and this would be a constant cat-and-mouse game with spammers that will distract us from working on other bug fixes and features, we don't have the resources at the moment for this.

For these reason, we will not implement this feature.
