### ISSUE TITLE
Delete content for groups results into the group disappearing entirely until a message is sent there

### ISSUE THREAD

**Issue by Mikaela** [wireapp/wire#314]
Hi, I got concerned about my old not-disappearing messages after reading [The Metadata Trap on the Intercept](https://theintercept.com/2019/08/04/whistleblowers-surveillance-fbi-trump/) and deleted content in all my apps and then I wasn't able to find my groups anymore until I asked people to send a message in them and I am still missing a few groups.

I am using Wire Desktop on one device (+ another one at my family) and Wire Android (two of them).

**Comment by nitrohorse** [comment]
A question comes to mind... how did you "delete content" in your apps?

**Comment by Mikaela** [comment]
On the main screen of Wire Android 3.35.814 I long touched all my chats and selected "Delete content..." (it's missing Finnish translation like "Leave group..." by the way) and in case of groups it asked whether to "delete content" or "delete content and leave" and I chose "delete content" and the group disappeared.

Interestingly one group survived this treatment visible on another phone that was powered off and I see full history in only that group on Wire Desktop 3.9.2895 on a laptop that wasn't running at the time.

**Comment by marcoconti83** [comment]
Hi @Mikaela 
When you to clear a conversation, all the messages are discarded and the conversation is removed from your list, but you are still part of that conversation - people can still write in that conversation, and you can find that conversation via the search.

If you want to get rid of the conversation so that it never comes back, you can leave the conversation then clear the content (depending on the platform, it will ask you if you also want to clear the conversation when you try to leave it).

I hope this clarifies!

**Comment by Mikaela** [comment]
No, I think you misunderstood my issue as the group was not findable from search or anywhere until another participant sent me a message

**Comment by marcoconti83** [comment]
The group should not be findable from anywhere until someone writes again - with the exception of the search. If you type the group name in the search it should show up in the search result. This is by design.

So it seems like there is a bug with the search - can you confirm whether you typed the conversation name in the search bar and it did not show up? Did you type the full name or just part of it?

**Comment by Mikaela** [comment]
A group I tested this with does show up in search now, so I guess it has been fixed.

I cannot test on Android due to https://github.com/wireapp/wire-android/issues/2321.
