### ISSUE TITLE
What happens if you message someone who doesn't have the app installed?

### ISSUE THREAD

**Issue by tallguy8819** [wireapp/wire#369]
Sorry if this is the wrong place for questions.

I'm just wondering what happens if I send a message to someone when they don't have the app installed? Someone who has an account and I have a conversation with them. I'm guessing they wouldn't see the message after signing back in?

**Comment by Transisto** [comment]
Yes, the new messages load when the app open, or get installed.

**Comment by marcoconti83** [comment]
Hi @tallguy8819 ,

Users who do not have the app installed will NOT be able to read messages send to them while the app was installed. This is due to Wire end-to-end encryption, which is the same thing that prevents the Wire backend (or anyone else) from reading those messages. You can find more details [here](https://wire.com/en/resources/whitepapers/security/).

You will only receive messages sent after you installed and logged in to the application.
