### ISSUE TITLE
Show Mobile Number in Profile

### ISSUE THREAD

**Issue by ch3ckmat3** [wireapp/wire#47]
We often have multiple phone numbers for many contacts, and need to know which mobile number is used to connect over Wire. A better option would be to link to that contact in Address Book in profile, and a button to open the contact details. Otherwise it is very confusing to see so many people in your Wire contacts and not able to know who is who.

**Comment by david-wire** [comment]
Thanks for the comment.
We are not planning on doing this for privacy reasons. Also:
- Auto-connections are Wire contacts whose phone number appears in your address book, or vice versa
- If a Wire connection is in your address book and you have shared it with Wire, you should see _name in Contacts_ (when looking at someone's profile information) to help you identify the actual connection
- Since it is possible to register and use Wire without a phone number (but with an email), usernames are unique identifiers and are searchable.
Therefore, this is not something we plan to do or add. Thanks again for the note.
