### ISSUE TITLE
Bug: Limit of number of devices is to low

### ISSUE THREAD

**Issue by user9209** [wireapp/wire#57]
Hello together,

I have the problem, that the number of devices that you can register on a single account is to low.
As I use 2+ PCs (Win + Linux) and 2 Notebooks (Win + Linux), a Tablet and a smartphone and on the PCs and Notebook also Windows and Linux, the current maximum device count of 7 is too small.
As each registration is independent on the hardware device, linux and windows take one slot.
Also the Web-Login would take some additional slots.

So please increase the limit to something like 14 / 20 or something like that.

Thanks in Advance

**Comment by user9209** [comment]
![aaaa](https://user-images.githubusercontent.com/9293951/27181169-a752a9c8-51d6-11e7-8a36-dfa1c7916320.PNG)

**Comment by david-wire** [comment]
Thanks for taking the time to send us your feedback. 

However, we are not planning on extending the current limit in the number of devices you can register to a Wire account. This is due to our current design and implementation of end-to-end encryption and we believe that this number (7 permanent and 1 temporary device) is enough for the vast majority of users.
